"use client";

import { useEffect, useId, useState } from "react";

// Client component that renders a Mermaid diagram definition to an SVG.
// We dynamically import `mermaid` (and run it only in the browser) so it never
// touches the server / SSR path. Each diagram gets a unique render id.
export default function Mermaid({ code }: { code: string }) {
  const reactId = useId();
  const renderId = `mermaid-${reactId.replace(/[:]/g, "")}`;
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        // Configure once. `startOnLoad: false` so we control rendering via render().
        mermaid.initialize({
          startOnLoad: false,
          theme: "default",
          securityLevel: "strict",
          fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        });

        // Validate + render. `render` returns a promise with { svg, bindFunctions }.
        const { svg } = await mermaid.render(renderId, code.trim());
        if (!cancelled) {
          setSvg(svg);
          setError("");
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
          setSvg("");
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, renderId]);

  if (error) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-4">
        <p className="text-sm font-medium text-red-700">
          Could not render diagram
        </p>
        <pre className="mt-2 overflow-auto whitespace-pre-wrap text-xs text-red-600">
          {error}
        </pre>
        <pre className="mt-3 overflow-auto rounded-lg bg-white/70 p-3 text-xs text-zinc-600">
          {code.trim()}
        </pre>
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="flex h-40 items-center justify-center rounded-xl bg-zinc-50 text-sm text-zinc-400">
        Rendering…
      </div>
    );
  }

  return (
    <div
      className="flex w-full justify-center overflow-x-auto rounded-xl bg-white p-4 [&_svg]:max-w-full [&_svg]:h-auto"
      // SVG is generated by mermaid from our own static .mmd content (no user input).
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
